[package]
name = "Waiter"
version = "0.1.0"
authors = ["Systool <systool@magisystem.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "~3.0.2"
dotenv = "^0.15.0"
simple_logger = "~1.9.0"
futures = "*"
jwt = "^0.10.0"
serde = "*"
log = "*"

[dependencies.sqlx]
version="0.4.0-beta.1"
default-features=false
features=[
	"macros",
	"migrate",
	"runtime-actix",
	"mysql",
	"json",
	"chrono"
]