[package]
name = "Waiter"
version = "0.1.0"
authors = ["Systool <systool@magisystem.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "~3.0.2"
dotenv = "^0.15.0"
