name: Waiter
description: A sample command-line application.
version: 0.4.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.1.1
  shelf_router: ^1.0.0
  shelf_helpers: 
    git: https://github.com/Kleak/shelf_helpers.git
  dotenv: ^3.0.0-nullsafety.0
  jose: ^0.3.2
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
