name: Waiter
description: A sample command-line application.
version: 0.4.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  shelf: ^1.1.1
  shelf_router: ^1.0.0
#  path: ^1.7.0

dev_dependencies:
  shelf_router_generator: ^1.0.0
  pedantic: ^1.9.0
  test: ^1.14.4
